# Documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md

version: '3.7'
services:

  database:
    image: docker.io/webpwnized/mutillidae:database
    networks:
      - datanet   

  database_admin:
    depends_on:
    - database
    image: docker.io/webpwnized/mutillidae:database_admin
    ports:
    - 127.0.0.1:81:80
    networks:
      - datanet   

  www:
    depends_on:
      - database
      - ldap
    image: docker.io/webpwnized/mutillidae:www
    volumes:
    # Make the Apache log files on the image available to localhost
      - "./www/var-log-apache2/:/var/log/apache2/"
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    networks:
      - datanet
      - ldapnet

  ldap:
    image: docker.io/webpwnized/mutillidae:ldap
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - ldapnet

  ldap_admin:
    depends_on:
      - ldap
    image: docker.io/webpwnized/mutillidae:ldap_admin
    ports:
      - 127.0.0.1:82:80
    networks:
      - ldapnet
   
volumes:
  ldap_data:
  ldap_config:

# Create network segments for the containers to use
networks:
    datanet:
    ldapnet:
